# =====================================================
# Head camera configuration
# =====================================================
# camera topic
head_camera:
  # camera config

  # if enable_zmq and enable_webrtc are both false, the camera will not start
  # Set to true to enable ZMQ publishing, false to disable
  enable_zmq: true
  # Port to publish camera stream, e.g. zmq tcp://*:55555.  image_client.py should connect to the same port
  zmq_port : 55555
  # Set to true to enable WebRTC publishing, false to disable
  enable_webrtc: false
  # Port for WebRTC signaling server
  webrtc_port : 60001

  # Type of camera:
  #   - "opencv"    → opencv driver
  #   - "realsense" → pyrealsense2 driver
  #   - "uvc"       → pyuvc driver
  type: opencv

  # Image Format
  # image resolution: [height, width]
  image_shape: [376, 1344] # [720, 2560]-60/30/15fps; [376, 1344]-100/60/30/15fps; [1080, 3840]-30/15fps; [1242, 4416]-15fps
  binocular: true
  # frame per second
  fps: 15

  # Camera identifiers (choose one or more):
  #   - video_id: X        → /dev/videoX  (e.g. 0 → /dev/video0)
  #   - serial_number: Y   → camera's hardware serial (e.g. 141722079879)
  #   - physical_path: Z   → sysfs physical USB path (e.g. /sys/devices/pci0000:00/.../1-11.2:1.0)
  #
  # Identifier priority:
  #   physical_path > serial_number > video_id
  #   if an identifier is not used, set it to null. The system will resolve the camera by priority.
  #
  # Notes:
  #   - type "realsense": supports serial_number only (but a RealSense can also be used as opencv/uvc if desired)
  #   - type "opencv":    supports video_id, serial_number, physical_path
  #   - type "uvc":       supports video_id, serial_number, physical_path
  video_id: 0
  serial_number: unknown
  physical_path : /sys/devices/platform/bus@0/3610000.usb/usb2/2-3/2-3.4/2-3.4.4/2-3.4.4:1.0